### ISSUE TITLE
Epic: error handling in frontend

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#398]

**Comment by marlonbaeten** [comment]
Proposed strategy:

- We introduce a [`ErrorBoundy`](https://legacy.reactjs.org/docs/error-boundaries.html) to catch and handle __unexpected__ errors 
- Apart from local errors/warnings (like form validation) we want - to escalate to / keep track of - a global error state for __expected__ errors: these come in two flavors:
    - Recoverable error (modal)
    - Unrecoverable error (page)
-  An error page or modal are rendered accordingly

We keep this error state global because they represent a state in out global state machine - which in our case is mainly dictated by the router. We want to prevent multiple error states at once.

**Comment by marlonbaeten** [comment]
Discussed with @lkleuver 

We introduce an `AppStateProvider` that hold global state, like the error state but also the currently selected locale.

Recoverable errors are rendered as a modal and do not trigger navigation,
unrecoverable errors show a full page message and have their own path

The "MVP" implementation for unrecoverable errors show a stack trace and full error message. An improvement for this in production is to encode the error information and show a QR code to the user, that allows them to communicate the exact error.
