### ISSUE TITLE
Backend CI runs are slow

### ISSUE THREAD

**Issue by cikzh** [kiesraad/abacus#488]
CI build times for the backend action have significantly increased. It seems there's a problem with caching

**Comment by praseodym** [comment]
I think this is mostly caused by the change to a release build for embedding frontend assets with `memory-serve` (#429). The release build takes significantly longer than a debug build and doesn't reuse the debug compilation already done for running `cargo test`.

I've asked @marlonbaeten to come up with a solution to have `memory-serve` embed assets for debug builds, which should allow us to bring down our CI runtimes again.
